// Code generated by goctl. DO NOT EDIT.

package model

import (
	"context"
	"database/sql"
	"fmt"
	"strings"
	"time"

	"github.com/zeromicro/go-zero/core/stores/builder"
	"github.com/zeromicro/go-zero/core/stores/cache"
	"github.com/zeromicro/go-zero/core/stores/sqlc"
	"github.com/zeromicro/go-zero/core/stores/sqlx"
	"github.com/zeromicro/go-zero/core/stringx"
)

var (
	shortUrlMapFieldNames          = builder.RawFieldNames(&ShortUrlMap{})
	shortUrlMapRows                = strings.Join(shortUrlMapFieldNames, ",")
	shortUrlMapRowsExpectAutoSet   = strings.Join(stringx.Remove(shortUrlMapFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), ",")
	shortUrlMapRowsWithPlaceHolder = strings.Join(stringx.Remove(shortUrlMapFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), "=?,") + "=?"

	cacheShortShortUrlMapIdPrefix   = "cache:short:shortUrlMap:id:"
	cacheShortShortUrlMapMd5Prefix  = "cache:short:shortUrlMap:md5:"
	cacheShortShortUrlMapSurlPrefix = "cache:short:shortUrlMap:surl:"
)

type (
	shortUrlMapModel interface {
		Insert(ctx context.Context, data *ShortUrlMap) (sql.Result, error)
		FindOne(ctx context.Context, id int64) (*ShortUrlMap, error)
		FindOneByMd5(ctx context.Context, md5 sql.NullString) (*ShortUrlMap, error)
		FindOneBySurl(ctx context.Context, surl sql.NullString) (*ShortUrlMap, error)
		Update(ctx context.Context, data *ShortUrlMap) error
		Delete(ctx context.Context, id int64) error
	}

	defaultShortUrlMapModel struct {
		sqlc.CachedConn
		table string
	}

	ShortUrlMap struct {
		Id       int64          `db:"id"`
		CreateAt time.Time      `db:"create_at"`
		CreateBy string         `db:"create_by"`
		IsDel    int64          `db:"is_del"` // 01
		Lurl     sql.NullString `db:"lurl"`
		Md5      sql.NullString `db:"md5"` // MD5
		Surl     sql.NullString `db:"surl"`
	}
)

func newShortUrlMapModel(conn sqlx.SqlConn, c cache.CacheConf) *defaultShortUrlMapModel {
	return &defaultShortUrlMapModel{
		CachedConn: sqlc.NewConn(conn, c),
		table:      "`short_url_map`",
	}
}

func (m *defaultShortUrlMapModel) Delete(ctx context.Context, id int64) error {
	data, err := m.FindOne(ctx, id)
	if err != nil {
		return err
	}

	shortShortUrlMapIdKey := fmt.Sprintf("%s%v", cacheShortShortUrlMapIdPrefix, id)
	shortShortUrlMapMd5Key := fmt.Sprintf("%s%v", cacheShortShortUrlMapMd5Prefix, data.Md5)
	shortShortUrlMapSurlKey := fmt.Sprintf("%s%v", cacheShortShortUrlMapSurlPrefix, data.Surl)
	_, err = m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("delete from %s where `id` = ?", m.table)
		return conn.ExecCtx(ctx, query, id)
	}, shortShortUrlMapIdKey, shortShortUrlMapMd5Key, shortShortUrlMapSurlKey)
	return err
}

func (m *defaultShortUrlMapModel) FindOne(ctx context.Context, id int64) (*ShortUrlMap, error) {
	shortShortUrlMapIdKey := fmt.Sprintf("%s%v", cacheShortShortUrlMapIdPrefix, id)
	var resp ShortUrlMap
	err := m.QueryRowCtx(ctx, &resp, shortShortUrlMapIdKey, func(ctx context.Context, conn sqlx.SqlConn, v any) error {
		query := fmt.Sprintf("select %s from %s where `id` = ? limit 1", shortUrlMapRows, m.table)
		return conn.QueryRowCtx(ctx, v, query, id)
	})
	switch err {
	case nil:
		return &resp, nil
	case sqlc.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultShortUrlMapModel) FindOneByMd5(ctx context.Context, md5 sql.NullString) (*ShortUrlMap, error) {
	shortShortUrlMapMd5Key := fmt.Sprintf("%s%v", cacheShortShortUrlMapMd5Prefix, md5)
	var resp ShortUrlMap
	err := m.QueryRowIndexCtx(ctx, &resp, shortShortUrlMapMd5Key, m.formatPrimary, func(ctx context.Context, conn sqlx.SqlConn, v any) (i any, e error) {
		query := fmt.Sprintf("select %s from %s where `md5` = ? limit 1", shortUrlMapRows, m.table)
		if err := conn.QueryRowCtx(ctx, &resp, query, md5); err != nil {
			return nil, err
		}
		return resp.Id, nil
	}, m.queryPrimary)
	switch err {
	case nil:
		return &resp, nil
	case sqlc.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultShortUrlMapModel) FindOneBySurl(ctx context.Context, surl sql.NullString) (*ShortUrlMap, error) {
	shortShortUrlMapSurlKey := fmt.Sprintf("%s%v", cacheShortShortUrlMapSurlPrefix, surl)
	var resp ShortUrlMap
	err := m.QueryRowIndexCtx(ctx, &resp, shortShortUrlMapSurlKey, m.formatPrimary, func(ctx context.Context, conn sqlx.SqlConn, v any) (i any, e error) {
		query := fmt.Sprintf("select %s from %s where `surl` = ? limit 1", shortUrlMapRows, m.table)
		if err := conn.QueryRowCtx(ctx, &resp, query, surl); err != nil {
			return nil, err
		}
		return resp.Id, nil
	}, m.queryPrimary)
	switch err {
	case nil:
		return &resp, nil
	case sqlc.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultShortUrlMapModel) Insert(ctx context.Context, data *ShortUrlMap) (sql.Result, error) {
	shortShortUrlMapIdKey := fmt.Sprintf("%s%v", cacheShortShortUrlMapIdPrefix, data.Id)
	shortShortUrlMapMd5Key := fmt.Sprintf("%s%v", cacheShortShortUrlMapMd5Prefix, data.Md5)
	shortShortUrlMapSurlKey := fmt.Sprintf("%s%v", cacheShortShortUrlMapSurlPrefix, data.Surl)
	ret, err := m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("insert into %s (%s) values (?, ?, ?, ?, ?)", m.table, shortUrlMapRowsExpectAutoSet)
		return conn.ExecCtx(ctx, query, data.CreateBy, data.IsDel, data.Lurl, data.Md5, data.Surl)
	}, shortShortUrlMapIdKey, shortShortUrlMapMd5Key, shortShortUrlMapSurlKey)
	return ret, err
}

func (m *defaultShortUrlMapModel) Update(ctx context.Context, newData *ShortUrlMap) error {
	data, err := m.FindOne(ctx, newData.Id)
	if err != nil {
		return err
	}

	shortShortUrlMapIdKey := fmt.Sprintf("%s%v", cacheShortShortUrlMapIdPrefix, data.Id)
	shortShortUrlMapMd5Key := fmt.Sprintf("%s%v", cacheShortShortUrlMapMd5Prefix, data.Md5)
	shortShortUrlMapSurlKey := fmt.Sprintf("%s%v", cacheShortShortUrlMapSurlPrefix, data.Surl)
	_, err = m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("update %s set %s where `id` = ?", m.table, shortUrlMapRowsWithPlaceHolder)
		return conn.ExecCtx(ctx, query, newData.CreateBy, newData.IsDel, newData.Lurl, newData.Md5, newData.Surl, newData.Id)
	}, shortShortUrlMapIdKey, shortShortUrlMapMd5Key, shortShortUrlMapSurlKey)
	return err
}

func (m *defaultShortUrlMapModel) formatPrimary(primary any) string {
	return fmt.Sprintf("%s%v", cacheShortShortUrlMapIdPrefix, primary)
}

func (m *defaultShortUrlMapModel) queryPrimary(ctx context.Context, conn sqlx.SqlConn, v, primary any) error {
	query := fmt.Sprintf("select %s from %s where `id` = ? limit 1", shortUrlMapRows, m.table)
	return conn.QueryRowCtx(ctx, v, query, primary)
}

func (m *defaultShortUrlMapModel) tableName() string {
	return m.table
}
